name: Run Continious Delivery action
run-name: CD action 
on:
  schedule:
    - cron: '35 7 * * 0-6'

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ DOCKER_GITHUB_USERNAME }}/minibus-be:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_GITHUB_USERNAME }}/minibus-be:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_GITHUB_USERNAME }}/minibus-be:buildcache,mode=max
